-- TRION ARENA online schema for Supabase
-- Run this whole file in the Supabase SQL Editor.
-- Then enable Authentication > Providers > Anonymous Sign-Ins.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '隊員' check (char_length(display_name) between 1 and 18),
  friend_code text not null unique check (char_length(friend_code) between 6 and 12),
  current_room_id uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (char_length(code) = 6),
  host_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'lobby' check (status in ('lobby','playing','finished')),
  settings jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  max_players integer not null default 8 check (max_players between 2 and 16),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz
);

alter table public.profiles
  drop constraint if exists profiles_current_room_id_fkey;
alter table public.profiles
  add constraint profiles_current_room_id_fkey foreign key (current_room_id) references public.rooms(id) on delete set null;

create table if not exists public.room_members (
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default '隊員' check (char_length(display_name) between 1 and 18),
  team integer not null default 0 check (team between 0 and 3),
  role text not null default 'combatant' check (role in ('combatant','operator','spectator')),
  ready boolean not null default false,
  player_config jsonb not null default '{}'::jsonb,
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.friends (
  owner_id uuid not null references auth.users(id) on delete cascade,
  friend_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (owner_id, friend_id),
  check (owner_id <> friend_id)
);

create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default '隊員',
  team_name text not null default '',
  mode text not null check (mode in ('solo','team')),
  score integer not null default 0 check (score between 0 and 100000000),
  kills integer not null default 0 check (kills between 0 and 100000),
  deaths integer not null default 0 check (deaths between 0 and 100000),
  match_id text not null default '',
  room_id uuid references public.rooms(id) on delete set null,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists rankings_mode_score_idx on public.rankings(mode, score desc);
create index if not exists room_members_room_idx on public.room_members(room_id);
create index if not exists friends_owner_idx on public.friends(owner_id);

alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.friends enable row level security;
alter table public.rankings enable row level security;

create or replace function public.is_room_member(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.room_members where room_id = target_room and user_id = auth.uid());
$$;

create or replace function public.is_room_host(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.rooms where id = target_room and host_id = auth.uid());
$$;

-- Profiles are private. Friend lookup and friend lists use security-definer RPCs.
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select to authenticated using (id = auth.uid());
drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own" on public.profiles for insert to authenticated with check (id = auth.uid());
drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- Rooms are readable by their host or current members. Joining is performed through join_room_by_code().
drop policy if exists "rooms readable" on public.rooms;
create policy "rooms readable" on public.rooms for select to authenticated using (host_id = auth.uid() or public.is_room_member(id));
drop policy if exists "rooms create host" on public.rooms;
create policy "rooms create host" on public.rooms for insert to authenticated with check (host_id = auth.uid());
drop policy if exists "rooms host update" on public.rooms;
create policy "rooms host update" on public.rooms for update to authenticated using (host_id = auth.uid()) with check (host_id = auth.uid());
drop policy if exists "rooms host delete" on public.rooms;
create policy "rooms host delete" on public.rooms for delete to authenticated using (host_id = auth.uid());

-- Members can read their lobby. The host can still read it after removing their own member row during host transfer.
drop policy if exists "members readable" on public.room_members;
create policy "members readable" on public.room_members for select to authenticated using (public.is_room_member(room_id) or public.is_room_host(room_id));
drop policy if exists "members join self" on public.room_members;
create policy "members join self" on public.room_members for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "members update self" on public.room_members;
create policy "members update self" on public.room_members for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "members leave self" on public.room_members;
create policy "members leave self" on public.room_members for delete to authenticated using (user_id = auth.uid());

-- Friend edges are private to their owner. The RPC creates reciprocal edges.
drop policy if exists "friends read own" on public.friends;
create policy "friends read own" on public.friends for select to authenticated using (owner_id = auth.uid());
drop policy if exists "friends delete own" on public.friends;
create policy "friends delete own" on public.friends for delete to authenticated using (owner_id = auth.uid());

-- Rankings are globally readable, but clients may only submit rows for themselves.
drop policy if exists "rankings readable" on public.rankings;
create policy "rankings readable" on public.rankings for select to authenticated using (true);
drop policy if exists "rankings insert own" on public.rankings;
create policy "rankings insert own" on public.rankings for insert to authenticated with check (user_id = auth.uid());

create or replace function public.join_room_by_code(
  room_code text,
  member_team integer,
  member_role text,
  member_name text,
  member_config jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_room public.rooms%rowtype;
  member_count integer;
begin
  if member_team < 0 or member_team > 3 then raise exception 'チーム指定が不正です。'; end if;
  if member_role not in ('combatant','operator','spectator') then raise exception '参加方法が不正です。'; end if;
  select * into target_room from public.rooms where upper(code) = upper(trim(room_code));
  if target_room.id is null then raise exception 'ルームが見つかりません。'; end if;
  if target_room.status = 'finished' then raise exception 'このルームは終了しています。'; end if;
  if target_room.status = 'playing' and member_role <> 'spectator' then raise exception '試合開始後は観戦参加だけ可能です。'; end if;
  select count(*) into member_count from public.room_members where room_id = target_room.id and user_id <> auth.uid();
  if member_count >= target_room.max_players then raise exception 'ルームが満員です。'; end if;
  insert into public.room_members(room_id,user_id,display_name,team,role,ready,player_config)
  values(target_room.id,auth.uid(),left(coalesce(nullif(trim(member_name),''),'隊員'),18),member_team,member_role,false,coalesce(member_config,'{}'::jsonb))
  on conflict(room_id,user_id) do update set
    display_name=excluded.display_name, team=excluded.team, role=excluded.role,
    ready=false, player_config=excluded.player_config;
  update public.profiles set current_room_id=target_room.id, updated_at=now() where id=auth.uid();
  return to_jsonb(target_room);
end;
$$;

create or replace function public.add_friend_by_code(target_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid;
begin
  select id into target_id from public.profiles where upper(friend_code) = upper(trim(target_code));
  if target_id is null then raise exception 'フレンドコードが見つかりません。'; end if;
  if target_id = auth.uid() then raise exception '自分自身は追加できません。'; end if;
  insert into public.friends(owner_id, friend_id) values (auth.uid(), target_id) on conflict do nothing;
  insert into public.friends(owner_id, friend_id) values (target_id, auth.uid()) on conflict do nothing;
  return target_id;
end;
$$;

create or replace function public.list_friends()
returns table (
  user_id uuid,
  display_name text,
  friend_code text,
  room_id uuid,
  room_code text,
  room_status text
)
language sql
security definer
set search_path = public
as $$
  select p.id, p.display_name, p.friend_code, r.id, r.code, r.status
  from public.friends f
  join public.profiles p on p.id = f.friend_id
  left join public.rooms r on r.id = p.current_room_id and r.status in ('lobby','playing')
  where f.owner_id = auth.uid()
  order by p.display_name;
$$;

grant execute on function public.is_room_member(uuid) to authenticated;
grant execute on function public.is_room_host(uuid) to authenticated;
grant execute on function public.join_room_by_code(text,integer,text,text,jsonb) to authenticated;
grant execute on function public.add_friend_by_code(text) to authenticated;
grant execute on function public.list_friends() to authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.rooms to authenticated;
grant select, insert, update, delete on public.room_members to authenticated;
grant select, delete on public.friends to authenticated;
grant select, insert on public.rankings to authenticated;
grant usage, select on sequence public.rankings_id_seq to authenticated;

-- Enable Realtime database notifications for lobby rows.
do $$
begin
  alter publication supabase_realtime add table public.rooms;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.room_members;
exception when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- v26 community/account migration
-- Safe to run repeatedly. Existing room, profile and ranking data is retained.
-- ---------------------------------------------------------------------------

alter table public.profiles add column if not exists username text;
create unique index if not exists profiles_username_unique_idx
  on public.profiles (lower(username)) where username is not null;

alter table public.rankings add column if not exists defense_round integer not null default 0;
alter table public.rankings drop constraint if exists rankings_mode_check;
alter table public.rankings
  add constraint rankings_mode_check check (mode in ('solo','team','defense'));

create table if not exists public.squads (
  id uuid primary key default gen_random_uuid(),
  name text not null default '新設隊' check (char_length(name) between 1 and 12),
  color text not null default '#4aa8ff' check (color ~ '^#[0-9A-Fa-f]{6}$'),
  emblem_pixels text not null default repeat('0',1024) check (char_length(emblem_pixels)=1024 and emblem_pixels ~ '^[01]+$'),
  leader_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.squad_members (
  squad_id uuid not null references public.squads(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (squad_id,user_id)
);

create index if not exists squad_members_user_idx on public.squad_members(user_id);

create table if not exists public.site_stats (
  id integer primary key default 1 check (id=1),
  access_count bigint not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.site_stats(id,access_count) values(1,0) on conflict(id) do nothing;

-- Used only by the public registration Edge Function through the service-role key.
create table if not exists public.registration_rate_limits (
  key_hash text primary key,
  window_started_at timestamptz not null default now(),
  attempts integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.squads enable row level security;
alter table public.squad_members enable row level security;
alter table public.site_stats enable row level security;
alter table public.registration_rate_limits enable row level security;

-- Community tables are read and modified through security-definer RPCs only.
drop policy if exists "squads direct access disabled" on public.squads;
drop policy if exists "squad members direct access disabled" on public.squad_members;
drop policy if exists "site stats direct access disabled" on public.site_stats;

create or replace function public.remove_friend(target_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'ログインが必要です。'; end if;
  delete from public.friends
  where (owner_id=auth.uid() and friend_id=target_id)
     or (owner_id=target_id and friend_id=auth.uid());
  return true;
end;
$$;

create or replace function public.list_my_squads()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(jsonb_agg(item order by item->>'name'),'[]'::jsonb)
  from (
    select jsonb_build_object(
      'id',s.id,
      'name',s.name,
      'color',s.color,
      'emblem_pixels',s.emblem_pixels,
      'leader_id',s.leader_id,
      'created_at',s.created_at,
      'updated_at',s.updated_at,
      'members',(
        select coalesce(jsonb_agg(jsonb_build_object(
          'user_id',m.user_id,
          'display_name',p.display_name,
          'friend_code',p.friend_code,
          'joined_at',m.joined_at
        ) order by m.joined_at),'[]'::jsonb)
        from public.squad_members m
        join public.profiles p on p.id=m.user_id
        where m.squad_id=s.id
      )
    ) as item
    from public.squads s
    where exists(
      select 1 from public.squad_members own
      where own.squad_id=s.id and own.user_id=auth.uid()
    )
  ) rows;
$$;

create or replace function public.create_squad_with_members(
  squad_name text,
  squad_color text,
  squad_emblem text,
  member_ids uuid[] default array[]::uuid[]
)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  new_id uuid;
  member_id uuid;
  clean_name text:=left(coalesce(nullif(trim(squad_name),''),'新設隊'),12);
  clean_color text:=case when coalesce(squad_color,'') ~ '^#[0-9A-Fa-f]{6}$' then squad_color else '#4aa8ff' end;
  clean_emblem text:=case when char_length(coalesce(squad_emblem,''))=1024 and squad_emblem ~ '^[01]+$' then squad_emblem else repeat('0',1024) end;
begin
  if auth.uid() is null then raise exception 'ログインが必要です。'; end if;
  insert into public.squads(name,color,emblem_pixels,leader_id)
  values(clean_name,clean_color,clean_emblem,auth.uid()) returning id into new_id;
  insert into public.squad_members(squad_id,user_id) values(new_id,auth.uid());
  foreach member_id in array coalesce(member_ids,array[]::uuid[]) loop
    if member_id<>auth.uid() and exists(
      select 1 from public.friends where owner_id=auth.uid() and friend_id=member_id
    ) then
      insert into public.squad_members(squad_id,user_id) values(new_id,member_id) on conflict do nothing;
    end if;
  end loop;
  return new_id;
end;
$$;

create or replace function public.update_squad_identity(
  target_squad uuid,
  squad_name text,
  squad_color text,
  squad_emblem text
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.squads where id=target_squad and leader_id=auth.uid()) then
    raise exception '隊長だけが隊設定を変更できます。';
  end if;
  update public.squads set
    name=left(coalesce(nullif(trim(squad_name),''),name),12),
    color=case when coalesce(squad_color,'') ~ '^#[0-9A-Fa-f]{6}$' then squad_color else color end,
    emblem_pixels=case when char_length(coalesce(squad_emblem,''))=1024 and squad_emblem ~ '^[01]+$' then squad_emblem else emblem_pixels end,
    updated_at=now()
  where id=target_squad;
  return true;
end;
$$;

create or replace function public.set_squad_leader(target_squad uuid,new_leader uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.squads where id=target_squad and leader_id=auth.uid()) then
    raise exception '現在の隊長だけが変更できます。';
  end if;
  if not exists(select 1 from public.squad_members where squad_id=target_squad and user_id=new_leader) then
    raise exception '隊員から新しい隊長を選んでください。';
  end if;
  update public.squads set leader_id=new_leader,updated_at=now() where id=target_squad;
  return true;
end;
$$;

create or replace function public.leave_squad(target_squad uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  next_leader uuid;
begin
  if not exists(select 1 from public.squad_members where squad_id=target_squad and user_id=auth.uid()) then
    raise exception 'この隊に所属していません。';
  end if;
  delete from public.squad_members where squad_id=target_squad and user_id=auth.uid();
  if not exists(select 1 from public.squad_members where squad_id=target_squad) then
    delete from public.squads where id=target_squad;
    return true;
  end if;
  if exists(select 1 from public.squads where id=target_squad and leader_id=auth.uid()) then
    select user_id into next_leader from public.squad_members where squad_id=target_squad order by joined_at limit 1;
    update public.squads set leader_id=next_leader,updated_at=now() where id=target_squad;
  end if;
  return true;
end;
$$;

create or replace function public.register_page_visit()
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  total bigint;
begin
  insert into public.site_stats(id,access_count,updated_at) values(1,1,now())
  on conflict(id) do update set access_count=public.site_stats.access_count+1,updated_at=now()
  returning access_count into total;
  return total;
end;
$$;

drop function if exists public.consume_registration_attempt(text,integer,integer);

create function public.consume_registration_attempt(
  p_rate_key text,
  p_max_attempts integer default 5,
  p_window_seconds integer default 3600
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  allowed boolean;
begin
  if p_rate_key is null or char_length(p_rate_key)<8 then return false; end if;
  if p_max_attempts<1 or p_window_seconds<60 then return false; end if;

  -- Serialize updates for the same key so simultaneous registration requests
  -- cannot bypass the counter.
  perform pg_advisory_xact_lock(hashtext(p_rate_key));

  insert into public.registration_rate_limits(key_hash,window_started_at,attempts,updated_at)
  values(p_rate_key,now(),1,now())
  on conflict(key_hash) do update set
    attempts=case
      when public.registration_rate_limits.window_started_at <= now()-make_interval(secs=>p_window_seconds) then 1
      else public.registration_rate_limits.attempts+1
    end,
    window_started_at=case
      when public.registration_rate_limits.window_started_at <= now()-make_interval(secs=>p_window_seconds) then now()
      else public.registration_rate_limits.window_started_at
    end,
    updated_at=now()
  returning attempts<=p_max_attempts into allowed;

  if random()<0.02 then
    delete from public.registration_rate_limits where updated_at<now()-interval '2 days';
  end if;
  return allowed;
end;
$$;

revoke all on function public.consume_registration_attempt(text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_registration_attempt(text,integer,integer) to service_role;

-- Make the new argument names visible to PostgREST immediately.
notify pgrst, 'reload schema';
grant execute on function public.remove_friend(uuid) to authenticated;
grant execute on function public.list_my_squads() to authenticated;
grant execute on function public.create_squad_with_members(text,text,text,uuid[]) to authenticated;
grant execute on function public.update_squad_identity(uuid,text,text,text) to authenticated;
grant execute on function public.set_squad_leader(uuid,uuid) to authenticated;
grant execute on function public.leave_squad(uuid) to authenticated;
grant execute on function public.register_page_visit() to authenticated;
